CREATE PROCEDURE 
AS 
BEGIN 

 IF OBJECT_ID('tempdb..#tFiliais') IS NOT NULL
  BEGIN 
    DROP TABLE #tFiliais
  END 

  DECLARE @DATA_INICIO_PERIODO DATETIME
        , @DATA_FIM_PERIODO    DATETIME
        , @CODIGO_PERIODO      INT 


  SELECT  @DATA_INICIO_PERIODO  =  DATA_INICIO_PERIODO
       ,  @DATA_FIM_PERIODO     =  DATA_FIM_PERIODO
       ,  @CODIGO_PERIODO       =  CODIGO_PERIODO
    FROM #tPeriodoComissao
   WHERE cCalculado ='0'

 
SELECT DISTINCT  CODIGO_FILIAL 
 INTO #tFiliais
  FROM LINX..LOJA_VENDA LV  WITH(NOLOCK) 
WHERE LV.DATA_HORA_CANCELAMENTO IS NOT NULL
  AND LV.TICKET_IMPRESSO = '1' 
  AND LV.DATA_VENDA BETWEEN @DATA_INICIO_PERIODO AND @DATA_FIM_PERIODO
  AND  NOT EXISTS ( SELECT TOP  1 1 
                        FROM WAREHOUSE..SHBI_TAB_DIM_FILIAIS  A
                       WHERE A.CODIGO_FILIAL =  LV.CODIGO_FILIAL  
                         AND ECOMMERCE = '1'  )

  DELETE SHBI_TAB_COM_FILIAIS
  WHERE CODIGO_PERIODO = @CODIGO_PERIODO
  
  INSERT INTO SHBI_TAB_COM_FILIAIS

   SELECT @CODIGO_PERIODO AS CODIGO_PERIODO
        , T.CODIGO_FILIAL
        , LOJV.FILIAL
        , FIL.REGIAO
        , (SELECT COUNT(1)
             FROM LINX..LOJA_VENDEDORES LVV WITH(NOLOCK)
            WHERE LVV.DATA_DESATIVACAO IS NULL
              AND LVV.CODIGO_FILIAL = T.CODIGO_FILIAL 
              AND DESC_CARGO LIKE '%VENDEDOR%' ) AS QTDE_VENDEDORAS 
        , (SELECT COUNT(1)
             FROM LINX..LOJA_VENDEDORES LVV WITH(NOLOCK)
            WHERE LVV.DATA_DESATIVACAO IS NULL
              AND LVV.CODIGO_FILIAL = T.CODIGO_FILIAL 
              AND  DESC_CARGO LIKE '%GERENTE%'  ) AS QTDE_GERENTE
         , ISNULL(WDF.TIPO_COMISSAO,'1') AS TIPO_COMISSAO 
         , IIF(CCF.UF = 'DF' , '1','0') AS DOBRA_DOMINGO 
     FROM #tFiliais T
          INNER JOIN LINX..LOJAS_VAREJO LOJV                   WITH(NOLOCK) ON LOJV.CODIGO_FILIAL = T.CODIGO_FILIAL  
          INNER JOIN LINX..FILIAIS FIL                         WITH(NOLOCK) ON FIL.FILIAL         = LOJV.FILIAL
          INNER JOIN LINX..CADASTRO_CLI_FOR CCF                WITH(NOLOCK) ON CCF.CLIFOR         = FIL.CLIFOR
          LEFT  JOIN WAREHOUSE..SHBI_TAB_DIM_FILIAIS WDF       WITH(NOLOCK) ON WDF.CODIGO_FILIAL  = T.CODIGO_FILIAL  
END 