SELECT *
FROM (

 

 SELECT 	A.CODCOLIGADA
      , CONVERT(VARCHAR(10), A.CHAPA) AS CHAPA
      , A.DTINICIO
      , ISNULL(A.DTFINAL,'20991231') AS DTFINAL
      , UPPER(B.DESCRICAO) AS TIPO
FROM RMCorpore_RHU.DBO.PFHSTAFT A
INNER JOIN RMCorpore_RHU.DBO.PCODAFAST B
	ON A.TIPO = B.CODINTERNO
INNER JOIN RMCorpore_RHU.DBO.PMUDSITUACAO C
	ON A.CODCOLIGADA = C.CODCOLIGADA
	AND A.MOTIVO = C.CODINTERNO
 
UNION ALL 

 SELECT 	A.CODCOLIGADA,  
	CONVERT(VARCHAR(10), A.CHAPA) AS CHAPA,  
	A.DATAINICIO, 
	A.DATAFIM, 
'FÉRIAS' AS TIPO  
FROM RMCorpore_RHU.DBO.PFUFERIASPER  A
INNER JOIN RMCorpore_RHU.DBO.PFUFERIAS B
	ON A.CODCOLIGADA = B.CODCOLIGADA
	AND A.CHAPA = B.CHAPA
	AND A.FIMPERAQUIS = B.FIMPERAQUIS) A
WHERE DTINICIO >='20140101'
OR DTFINAL  >='20140101'