 SELECT 
	CASE WHEN ISNULL(C.TKT_UNICO, 'OK') = 'OK' THEN 'NÃO' ELSE C.TKT_UNICO END AS TKT_UNICO,
	CONVERT(VARCHAR(10), D.PEDIDO) AS LJVV_B2CPEDIDO,
	A.CODIGO_FILIAL + A.TERMINAL + CONVERT(CHAR(7), A.LANCAMENTO_CAIXA)	AS _ID_LJVV_CHAVEF,
	A.CODIGO_FILIAL + A.TICKET + CONVERT(VARCHAR(25), A.DATA_VENDA,112) AS _ID_LJVV_CHAVEP,
	CONVERT(VARCHAR(7), A.LANCAMENTO_CAIXA) AS LJVV_LANCCX,
	A.DATA_DIGITACAO					AS LJVV_DTDIGITACAO,
    A.CODIGO_CLIENTE 					AS _ID_CLIVAR_CODIGO,
	A.TERMINAL							AS LJVV_TERMINAL,
    A.CODIGO_FILIAL 					AS _ID_FILIAL_CODIGO,
    B.FILIAL 							AS _ID_FILIAL_NOME,
    A.CODIGO_TAB_PRECO 					AS _ID_TABPRE_CODIGO,
    A.CPF_CGC_ECF 						AS LJVV_CPFCGCECF,
    A.DATA_HORA_CANCELAMENTO 			AS LJVV_DTCANC,
    DAY(A.DATA_HORA_CANCELAMENTO) 		AS LJVV_DTCANC_DIA,
    MONTH(A.DATA_HORA_CANCELAMENTO) 	AS LJVV_DTCANC_MES,
    YEAR(A.DATA_HORA_CANCELAMENTO) 		AS LJVV_DTCANC_ANO,            
    A.DATA_VENDA						AS LJVV_DTVENDA,
    DAY(A.DATA_VENDA)					AS LJVV_DTVENDA_DIA,
    MONTH(A.DATA_VENDA)					AS LJVV_DTVENDA_MES,
    YEAR(A.DATA_VENDA)					AS LJVV_DTVENDA_ANO,            
    A.DESCONTO							AS LJVV_VLRDESCON,
    A.GERENTE_LOJA						AS LJVV_GERENTE,
    A.OPERACAO_VENDA					AS LJVV_OPVENDA,
    A.QTDE_TOTAL						AS LJVV_QTPECAS,
    A.QTDE_TROCA_TOTAL					AS LJVV_QTTROCA,
  	CONVERT(VARCHAR(8), A.TERMINAL)		AS _ID_LJTERMN_TERMINAL, 
    A.TICKET							AS _ID_LJVV_TICKET,
    A.TOTAL_QTDE_CANCELADA				AS LJVV_QTCANCEL,
   	A.QTDE_PONTOS_ACUMULADOS			AS LJVV_PTOS_ACUMULADOS,
  	A.QTDE_PONTOS_RESGATADOS			AS LJVV_PTOS_RESGATADOS,
    A.VALOR_CANCELADO					AS LJVV_VLCANCEL,
    VVG.VALOR_PAGO						AS LJVV_VLPAGO,
    A.VALOR_TIKET						AS LJVV_VLTICKET,
    VVG.VALOR_TROCA						AS LJVV_VLTROCA,
    A.VALOR_VENDA_BRUTA					AS LJVV_VLVNBRUT,
    CONVERT(VARCHAR(4), A.VENDEDOR)		AS _ID_LJVD_CODIGO,
	VVG.GRIFFE							AS LJVV_GRIFFE
FROM LINX..LOJA_VENDA A WITH(NOLOCK)
INNER JOIN LINX..LOJAS_VAREJO B WITH(NOLOCK)
	ON A.CODIGO_FILIAL = B.CODIGO_FILIAL
LEFT JOIN (
			SELECT 'SIM' AS TKT_UNICO, A.CODIGO_FILIAL, A.DATA_VENDA, A.TICKET
			FROM LINX..LOJA_VENDA A WITH(NOLOCK)
			INNER JOIN (SELECT CODIGO_FILIAL, DATA_VENDA, TICKET FROM LINX..LOJA_VENDA_PRODUTO WITH(NOLOCK) WHERE PRODUTO LIKE '121300020') B 
				ON A.CODIGO_FILIAL = B.CODIGO_FILIAL
				AND A.DATA_VENDA = B.DATA_VENDA
				AND A.TICKET = B.TICKET
			INNER JOIN LINX..LOJA_VENDA_PRODUTO C WITH(NOLOCK)
				ON A.CODIGO_FILIAL = C.CODIGO_FILIAL
				AND A.DATA_VENDA = C.DATA_VENDA
				AND A.TICKET = C.TICKET
			GROUP BY A.CODIGO_FILIAL, A.DATA_VENDA, A.TICKET HAVING COUNT(DISTINCT C.PRODUTO) = 1
			) C
	ON A.CODIGO_FILIAL = C.CODIGO_FILIAL
	AND A.TICKET = C.TICKET
	AND A.DATA_VENDA = C.DATA_VENDA
LEFT JOIN (SELECT DISTINCT PEDIDO, CODIGO_FILIAL, TICKET, DATA_VENDA FROM LINX..LOJA_PEDIDO_VENDA WITH(NOLOCK) WHERE CODIGO_FILIAL_ORIGEM = 'B2C001') D
	ON A.CODIGO_FILIAL = D.CODIGO_FILIAL
	AND A.TICKET = D.TICKET
	AND A.DATA_VENDA = D.DATA_VENDA
	INNER JOIN LINX..SHBI_VIEW_VENDAS_VAREJO_GRIFFE VVG WITH(NOLOCK) 
		ON A.CODIGO_FILIAL = VVG.CODIGO_FILIAL 
		AND	A.TICKET = VVG.TICKET 
		AND A.DATA_VENDA = VVG.DATA_VENDA 	
--Where 
--	A.DATA_VENDA>=DATEADD(D,-$(v_Dias),CONVERT(NVARCHAR(10),GETDATE(),112))